[package]
name = "audio_engine"
version = "0.1.0"
edition = "2024"

[lib]
name = "audio_engine"
path = "src/lib.rs"

[dependencies]
cpal = "0.17.3"
ringbuf = "0.4.8"
rubato = "=0.16.0"
voice_activity_detector = "0.2.1"
tokio = { version = "1", features = ["full", "time"] }
tokio-stream = "0.1.18"
anyhow = "1"
webrtc-audio-processing = { version = "2.0.4", features = ["bundled"] }
webrtc-audio-processing-config = "2.0.4"